"""World Bible extraction and validation for chapter-based VN production.

A World Bible is the canonical reference for all chapters — it locks down
characters, locations, stats, art style, and plot arc so that every chapter
generated by the pipeline stays coherent.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def extract_world_bible(gdd: dict, output_path: Path | None = None) -> dict:
    """Extract a canonical World Bible from a full-game GDD.

    The bible contains everything that MUST stay consistent across chapters:
    - World setting, time period, tone
    - Character roster (appearance, personality, arcs)
    - Locations
    - Stat system
    - Art style guide (for ComfyUI prompt consistency)
    - Music mood guide
    - High-level plot arc with key events
    """
    chars = []
    for c in gdd.get("character_roster", []):
        chars.append({
            "id": _slug(c.get("name", "unknown")),
            "name": c.get("name", "Unknown"),
            "role": c.get("role", "supporting"),
            "description": c.get("description", ""),
            "personality": c.get("personality", ""),
            "visual": c.get("visual_description", c.get("description", "")),
            "route": c.get("route", ""),
            "arc_summary": c.get("arc", ""),
        })

    locations = []
    for s in gdd.get("scenes", []):
        locations.append({
            "id": _slug(s.get("name", "unknown")),
            "name": s.get("name", "Unknown"),
            "description": s.get("description", ""),
            "mood": s.get("mood", "neutral"),
        })

    stat_system = gdd.get("stat_system", {})
    stats = []
    for s in stat_system.get("stats", []):
        stats.append({
            "name": s.get("name"),
            "display_name": s.get("display_name", s.get("name", "")),
            "range": s.get("range", [0, 100]),
            "decay": s.get("decay", 0),
            "description": s.get("description", ""),
        })

    protagonist = gdd.get("player_protagonist", {})
    routes = gdd.get("route_structure", {}).get("character_routes", [])

    bible = {
        "title": gdd.get("title", "Visual Novel"),
        "genre": gdd.get("genre", "visual-novel"),
        "version": "1.0",
        "world": {
            "setting": gdd.get("narrative_premise", ""),
            "tone": gdd.get("progression", ""),
            "core_loop": gdd.get("core_loop", []),
        },
        "protagonist": {
            "name": protagonist.get("name", "Player"),
            "background": protagonist.get("background", ""),
            "motivation": protagonist.get("motivation", ""),
        },
        "characters": chars,
        "locations": locations,
        "stats": stats,
        "routes": [
            {
                "id": _slug(r.get("name", f"route_{i}")),
                "name": r.get("name", f"Route {i}"),
                "heroine": r.get("heroine", ""),
                "theme": r.get("theme", ""),
            }
            for i, r in enumerate(routes)
        ],
        "plot_arc": {
            "act1_setup": gdd.get("narrative_premise", "")[:500],
            "key_events": gdd.get("cg_milestones", []),
            "ending_paths": [
                ec.get("name", f"ending_{i}")
                for i, ec in enumerate(gdd.get("ending_conditions", []))
            ],
        },
        "art_style": _extract_art_style(gdd),
        "music_mood": _extract_music_mood(gdd),
        "writing_tone": {
            "language": "zh-CN",
            "style": "Literary Chinese prose, present tense, intimate POV",
            "register": "Dark, politically charged, with moments of tenderness",
            "dialogue_length_chars": [200, 400],
        },
    }

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(bible, indent=2, ensure_ascii=False))
    return bible


def _slug(text: str) -> str:
    import re
    return re.sub(r"[^a-z0-9_]+", "_", text.lower()).strip("_")


def _extract_art_style(gdd: dict) -> dict:
    art = gdd.get("art_style", {})
    return {
        "character": art.get("character_style", "anime visual novel, detailed face, expressive eyes"),
        "background": art.get("background_style", "cinematic dystopian cityscape, neon and shadow"),
        "color_palette": art.get("color_palette", "dark blues, warm oranges, deep reds"),
        "negative_prompt": (
            "blurry, low quality, distorted, ugly, bad anatomy, "
            "watermark, text, signature, realistic, photo, 3d render"
        ),
    }


def _extract_music_mood(gdd: dict) -> dict:
    audio = gdd.get("audio", {})
    return {
        "bgm_genre": audio.get("genre", "ambient electronic, dark synth"),
        "mood_per_scene": {
            "tense": "minor key, low synth pulse",
            "romantic": "soft piano, warm strings",
            "triumphant": "rising brass, full orchestra",
            "melancholic": "solo cello, sparse piano",
            "hopeful": "acoustic guitar, gentle piano",
        },
    }


def validate_chapter_against_bible(chapter_data: dict, bible: dict) -> list[str]:
    """Check that a chapter's generated data is consistent with the world bible."""
    errors = []

    valid_char_names = {c["name"] for c in bible.get("characters", [])}
    valid_char_names.add(bible.get("protagonist", {}).get("name", "Player"))

    valid_stat_names = {s["name"] for s in bible.get("stats", [])}

    valid_location_ids = {loc["id"] for loc in bible.get("locations", [])}

    branching = chapter_data.get("branching", {})
    for node_id, node in branching.get("nodes", {}).items():
        if not isinstance(node, dict):
            continue
        scene_key = node.get("scene_key", "")
        if scene_key and valid_location_ids and scene_key not in valid_location_ids:
            pass

        for choice in node.get("choices", []):
            if not isinstance(choice, dict):
                continue
            for stat_name in choice.get("stat_deltas", {}).keys():
                if stat_name not in valid_stat_names:
                    errors.append(
                        f"Chapter node {node_id}: stat '{stat_name}' not in bible"
                    )

    dialogue = chapter_data.get("dialogue", {})
    for dlg_id, dlg in dialogue.items():
        if isinstance(dlg, dict):
            speaker = dlg.get("speaker", "")
            if speaker and speaker not in valid_char_names and speaker not in (
                "Narrator", "旁白", "narrator", "System", "系统"
            ):
                errors.append(
                    f"Dialogue {dlg_id}: speaker '{speaker}' not in bible character roster"
                )

    return errors


def load_bible(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def merge_chapter_bibles(base_bible: dict, *chapter_bibles: dict) -> dict:
    """Merge multiple chapter bibles, with chapters taking precedence for new data."""
    merged = json.loads(json.dumps(base_bible))
    for ch_bible in chapter_bibles:
        for key, val in ch_bible.items():
            if key not in merged or not merged[key]:
                merged[key] = val
            elif isinstance(val, list) and isinstance(merged[key], list):
                existing_ids = {
                    item.get("id") or item.get("name")
                    for item in merged[key] if isinstance(item, dict)
                }
                for item in val:
                    if isinstance(item, dict):
                        item_id = item.get("id") or item.get("name")
                        if item_id not in existing_ids:
                            merged[key].append(item)
                            existing_ids.add(item_id)
                    else:
                        merged[key].append(item)
    return merged
